//
//  ZKProof.swift
//  ZKProofOfConcept
//
//  Created by Ronald "Danger" Mannak on 5/29/19.
//  Copyright © 2019 A Puzzle A Day. All rights reserved.
//

import Foundation


/**
 
 JSON structure as generated by ZoKrates
 {
 "proof": {
 "a": ["0x01fbf9316f0e7ad963380cb9848903b509b377d3e19a3f37d7ff119bc3538b74", "0x2e4deb18854977ab26c836d1aae7895acf30ad33b0938706182acfe425fa9e33"],
 "b": [["0x20b2580d1fd2d0054d26a890b8f0eac2f46993dace3754897fd506b57c739637", "0x15a2fddadfd2d50df2fda269b0b5cc8aead2c36e7c437dbdac3dd30affe3012b"], ["0x0dd09acbe772ae048d26b0883446a27a9b81ee48ded2a294543a04b3155cbf9e", "0x085ed74a4e6f43b938cb20720d646c48b1c05b637061e146daae2e6cad637688"]],
 "c": ["0x2fcaae533de750e7f63029ce33aa44cb3082b2205bb47921fe72ff34713e3270", "0x1bf90435e413a15d31cb416bab2a8450688aec1af2c816248de0b67fc60acd42"]
 },
 "inputs": ["0x0000000000000000000000000000000000000000000000000000000000000001"]
 }
 */
public struct ZKProof: Codable, Equatable {
    
    let a: [String]
    let b: [String]
    let c: [String]
    
    let inputs: [String]
}

public extension ZKProof {
    
    func validate() -> Bool {
        return false
    }
}

extension ZKProof: Sha256Hashable {
    
    public var sha256:      Sha256Hash {
        return try! JSONEncoder().encode(self).sha256
    }
}
